# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# test platform: OSX-M1
name: Aviary

channels:
  - conda-forge

dependencies:
  - python>=3.7
  - numpy>=1.17.*
  - pandas>=0.23.*
  - shapely>=1.6.*
  - geojson>=2.5.*
  - geographiclib>=1.5.*
  - pyproj>=2.2.*
  - pytest>=4.1.*
  - pip
  - pip:
    - jsonpath_rw_ext>=1.2.*